version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nl.jqno.equalsverifier:equalsverifier
    versions:
    - 3.5.2
