name: Java Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Show versions
      run: ./mvnw -version && gpg --version

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: ./mvnw clean package javadoc:jar -U -B --file pom.xml
